### ISSUE TITLE
Duration class no compile correctly

### ISSUE THREAD

**Issue by neo-clon** [voorjaar/svelte-windicss-preprocess#2]
Hi again!

I'm testing various classes and see that duration not is passed in compile time, only on interpreted

![image](https://user-images.githubusercontent.com/12282168/103831319-6efb6e80-5041-11eb-9b58-847a16401691.png)

![image](https://user-images.githubusercontent.com/12282168/103831335-76227c80-5041-11eb-976e-c694ba816e41.png)

**Comment by voorjaar** [comment]
https://github.com/voorjaar/windicss/commit/9a0bc2a6a78f64a36ff3778a37ffe9d63ef80714 should fix this.

**Comment by voorjaar** [comment]
The svelte preprocess plugin has also been updated https://github.com/voorjaar/svelte-windicss-preprocess/commit/02fc3bcbf8d6257b8b1f282b1c9812220475271d, so all dependencies should be updated.
