### ISSUE TITLE
Cannot handle multiline classes

### ISSUE THREAD

**Issue by juanvillacortac** [voorjaar/svelte-windicss-preprocess#3]
Example:

```html
<button
  on:click={increment}
  class="
    rounded-2em
    px-2em
    py-1em
    bg-orange-200
  "
  >Clicks: {count}</button
>
```

This doesn't generate the expected output

**Comment by voorjaar** [comment]
https://github.com/voorjaar/windicss/commit/ecf1ed0033151585538d187e8ec5edb263ef07f8 fix this.

This improvement will be released with the next version, please wait a moment.
