### ISSUE TITLE
CSS Pseudo-classes not supported

### ISSUE THREAD

**Issue by juanvillacortac** [voorjaar/svelte-windicss-preprocess#6]
Pseudo-classes like `:hover`, `:first` or `:focus` doesn't work.

A code like this doesn't make effect:

```svelte
<h1>Hello world!</h1>

<style>
  /* Doesn't works */
  h1:hover {
    @apply text-red-500;
    /* Or simply `color: red;` */
  }

/* But, @variants works */
  @variants hover {
    h1 {
      @apply text-red-500;
      /* Or simply `color: red;` */
    }
  }
</style>
```

I think that should affect other CSS statements like `:not(.class)`, but I not tested it yet, so I'm not very sure.

**Comment by voorjaar** [comment]
Sorry, I made a stupid mistake by escaping class name. https://github.com/voorjaar/svelte-windicss-preprocess/commit/d188b7dd27b80d7ba8c6df1131266f887a563907 should fix it.

**Comment by juanvillacortac** [comment]
I tested the update, and it works, but in certains conditions, like:

```svelte
<h1>Hello world!</h1>

<style>
  /* Doesn't works */
  h1:hover {
    @apply text-red-500;
  }

  /* But, without directives inside, works fine */
  h1:hover {
    color: red;
  }
</style>
```

I think that the parser needs to discriminate correct cases for escaping class names between a windicss class as a class gnerated by `hover:text-red-500` and `h1:hover` when is parsed for having a directive.

**Comment by voorjaar** [comment]
https://github.com/voorjaar/windicss/commit/e7b2339a2256bc7136aca6aae0b2016ed8396697 now it works.
