### ISSUE TITLE
Error when creating a sapper project 

### ISSUE THREAD

**Issue by stilet** [voorjaar/svelte-windicss-preprocess#7]
`(node:9014) UnhandledPromiseRejectionWarning: Error: Cannot find module '../../src/index'`

**Comment by voorjaar** [comment]
This is a document error. You need to change '../../src/index' to 'svelte-windicss-preprocess'.

See details, https://github.com/voorjaar/svelte-windicss-preprocess/commit/42341d0bfcfca6b3a27f7f0df357304b6ea75e76.
