### ISSUE TITLE
base tailwind variables

### ISSUE THREAD

**Issue by xinsight** [voorjaar/svelte-windicss-preprocess#8]
I followed the install instructions and most of of tailwind works, but I noticed that I couldn't get the `ring` class to work with windicss.

For example, if I have run a file with a single file with `<div class="ring-2" />` i get:

```
.ring-2 {
  -webkit-box-shadow: var(--tw-ring-inset) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color);
  box-shadow: var(--tw-ring-inset) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color);
}
```

But nothing appears as i suspect the css vars like `--tw-ring-color` and are not defined. This is likely a noob tailwindcss configuration issue, as I'm not sure how the base tailwind imports in a svelte project with windicss. Any ideas?

**Comment by voorjaar** [comment]
I think you're right. I must have missed something when defining this utility. I'll fix this problem later when I release a new version. please wait a moment. By the way, windicsss are a complete refactoring of tailwindcss.

**Comment by xinsight** [comment]
Yes, i started to look at the source code and realized that you had completely replaced tailwindcss. But windicss is so fast, it's totally worth a few hiccups! :)

**Comment by voorjaar** [comment]
https://github.com/voorjaar/windicss/commit/4fa095b75518b8a313fcd467eafe53a76b633b87 fix this.
